import {
  VehicleCategory,
  DetailingPackage,
  ServiceAddon,
  DetailBay,
  BookingRecord,
  FleetAccount,
  QuoteDripStep,
} from "./types";

export const VEHICLE_CATEGORIES: VehicleCategory[] = [
  {
    id: "coupe",
    name: "Coupe & Sports Car",
    description: "2-door precision performance & supercars",
    multiplier: 1.0,
    popularModels: "Porsche 911, Corvette, Ferrari F8, BMW M4",
    iconName: "Car",
  },
  {
    id: "sedan",
    name: "Luxury Sedan",
    description: "Mid & full-size executive passenger vehicles",
    multiplier: 1.15,
    popularModels: "Mercedes S-Class, BMW 7-Series, Tesla Model S, Audi RS7",
    iconName: "CarFront",
  },
  {
    id: "suv",
    name: "Executive SUV",
    description: "Mid to large sport utilities & crossovers",
    multiplier: 1.3,
    popularModels: "Range Rover, Porsche Cayenne, Escalade, G-Wagon",
    iconName: "Truck",
  },
  {
    id: "truck",
    name: "Full-Size / Dually",
    description: "Heavy-duty luxury pickups & crew cabs",
    multiplier: 1.45,
    popularModels: "Ford F-150 Raptor, RAM TRX, GMC Denali 2500",
    iconName: "TruckFront",
  },
  {
    id: "fleet",
    name: "Commercial Fleet",
    description: "Multi-vehicle commercial vans & fleet units",
    multiplier: 1.25,
    popularModels: "Mercedes Sprinter, Transit Executive, Chauffeur Fleet",
    iconName: "Caravan",
  },
];

export const DETAILING_PACKAGES: DetailingPackage[] = [
  {
    id: "ceramic-signature",
    name: "Signature 5-Year Graphene Ceramic",
    badge: "Most Popular on Meta Ads",
    tagline: "Ultra-slick 10H hydrophobic armor with extreme mirror depth & self-healing gloss.",
    basePrice: 1250,
    durationHours: 12,
    warrantyYears: 5,
    recommendedFor: "Owners seeking multi-year swirl-free paint preservation and zero waxing.",
    features: [
      "Multi-stage decontamination & clay bar exfoliation",
      "2-Stage Dual-Action Paint Correction (removes up to 90% swirls & holograms)",
      "System X Max 10H / Graphene dual-coat ceramic infusion",
      "Wheel faces ceramic sealed & caliper detailing",
      "Windshield hydrophobic ceramic rain shield (12-month)",
      "Carfax registered warranty & digital certificate",
    ],
  },
  {
    id: "connoisseur-full",
    name: "The Connoisseur Concierge Overhaul",
    badge: "Flagship Luxury",
    tagline: "The absolute pinnacle of automotive restoration: Exterior paint, leather sanctuary & engine bay.",
    basePrice: 1850,
    durationHours: 16,
    warrantyYears: 7,
    recommendedFor: "Exotics, collector cars, and executive vehicles demanding showroom perfection.",
    features: [
      "Includes everything in Signature 5-Year Ceramic",
      "Full 3-Stage Jeweling Paint Correction (98%+ perfection)",
      "Interior Leather deep steam extraction & Swissvax hide nourishment",
      "Interior leather & Alcantara ceramic protection barrier",
      "Deep Engine Bay cryogenic or dry-steam decontamination & satin dressing",
      "Underbody chassis salt & grime flush",
      "VIP complimentary loaner concierge / enclosed transport option",
    ],
  },
  {
    id: "paint-correction-pro",
    name: "Paint Correction & Gloss Revival",
    tagline: "Restore optical clarity, erase wash marring, and unleash true color saturation.",
    basePrice: 750,
    durationHours: 8,
    recommendedFor: "Vehicles with haze, swirls, and micro-scratches needing correction before sealing.",
    features: [
      "PH-neutral foam bath & iron particle chemical decontamination",
      "Precision paint gauge depth analysis per panel",
      "2-Stage rotary & DA compounding and fine finishing polish",
      "12-Month polymer sealant with UV inhibitors",
      "Trim reconditioning & deep tire satin conditioning",
    ],
  },
  {
    id: "interior-executive",
    name: "Executive Leather & Interior Restoration",
    tagline: "Clinical sterilization, rich leather conditioning, and zero artificial greasy scents.",
    basePrice: 450,
    durationHours: 5,
    recommendedFor: "High-end cabins needing deep sanitization, stain removal, and matte OEM finish.",
    features: [
      "High-pressure vapor dry-steam sanitized vents & crevices",
      "Italian leather PH-balanced scrub & conditioning cream",
      "Hot-water extraction of deep carpet fibers and floor mats",
      "Medical-grade ozone odor elimination treatment",
      "UV matte finish barrier on dashboard & consoles",
    ],
  },
  {
    id: "fleet-shield",
    name: "Fleet & Commercial Priority Care",
    badge: "B2B Volume",
    tagline: "Turnkey monthly maintenance program for luxury chauffeur, executive, and delivery fleets.",
    basePrice: 280,
    durationHours: 3,
    recommendedFor: "Corporate fleets requiring regular sanitization and immaculate public image.",
    features: [
      "Scheduled bi-weekly or monthly mobile/bay service",
      "Spot swirl reduction & ceramic maintenance booster wash",
      "Rapid interior disinfection & glass clarity polish",
      "Consolidated B2B monthly invoicing & priority bay reserving",
      "Dedicated account manager & 24hr emergency slot reserve",
    ],
  },
];

export const SERVICE_ADDONS: ServiceAddon[] = [
  {
    id: "wheel-ceramic",
    name: "Wheel Barrels & Calipers Ceramic",
    description: "Wheels off deep clean + 9H ceramic coating resisting 1200°F brake dust",
    price: 320,
    durationMinutes: 90,
    category: "protection",
  },
  {
    id: "glass-coating",
    name: "Full Exterior Glass FlyBy Hydrophobic Shield",
    description: "Hyper-repellent rain coating for panoramic roof, windshield & side windows",
    price: 180,
    durationMinutes: 45,
    category: "exterior",
  },
  {
    id: "interior-coating",
    name: "Full Leather & Fabric Ceramic Shield",
    description: "Repels dye transfer, coffee, ink, and UV fading for 2 years",
    price: 260,
    durationMinutes: 60,
    category: "interior",
  },
  {
    id: "engine-bay",
    name: "Dry-Ice / Steam Engine Bay Restoration",
    description: "Detailed degreasing with zero-water risks and OEM satin preservation",
    price: 195,
    durationMinutes: 60,
    category: "exterior",
  },
  {
    id: "headlight-ppf",
    name: "Headlight & Foglight Self-Healing PPF",
    description: "Optical clear film preventing rock chips, pitting, and yellow UV oxidation",
    price: 240,
    durationMinutes: 45,
    category: "protection",
  },
  {
    id: "ozone-sterilization",
    name: "Heavy-Duty Ozone Purifier & Odor Bomb",
    description: "Permanently annihilates smoke, pet, and biological odors at molecular level",
    price: 120,
    durationMinutes: 45,
    category: "interior",
  },
];

export const DETAIL_BAYS: DetailBay[] = [
  {
    id: "bay-1",
    name: "VIP Bay 1 - Ceramic Cleanroom",
    specialty: "Climate-controlled 68°F dust-free infrared curing suite",
    maxPerDay: 2,
  },
  {
    id: "bay-2",
    name: "VIP Bay 2 - Paint Correction Studio",
    specialty: "High CRI 5000K inspection lighting bank for scratch jewel finish",
    maxPerDay: 2,
  },
  {
    id: "bay-3",
    name: "VIP Bay 3 - Interior & Prep Suite",
    specialty: "Dry-vapor steam extraction & upholstery conditioning",
    maxPerDay: 3,
  },
  {
    id: "mobile-unit",
    name: "Concierge Mobile Unit 1",
    specialty: "Self-powered deionized water & silent inverter van dispatched to client",
    maxPerDay: 2,
  },
];

export const INITIAL_BOOKINGS: BookingRecord[] = [
  {
    id: "LX-94821",
    createdAt: "2026-10-02T10:15:00Z",
    customerName: "Julian Vance",
    customerEmail: "j.vance@vancemetals.com",
    customerPhone: "(415) 883-2901",
    vehicleType: "coupe",
    vehicleDetails: {
      year: "2024",
      make: "Porsche",
      model: "911 GT3 RS",
      color: "Shark Blue",
    },
    servicePackageId: "connoisseur-full",
    addons: ["wheel-ceramic", "glass-coating"],
    totalPrice: 2350,
    depositAmount: 500,
    scheduledDate: "2026-10-18",
    timeSlot: "08:30 AM",
    bayId: "bay-1",
    status: "deposit_paid",
    leadSource: "Meta Ad: 5Y Ceramic",
    followUpStep: 3,
    notes: "Requires enclosed trailer drop-off. Client prefers no high-gloss tire shine, only satin OEM look.",
    isMobileService: false,
  },
  {
    id: "LX-83910",
    createdAt: "2026-10-03T14:40:00Z",
    customerName: "Elena Rostova",
    customerEmail: "elena@apexholdings.io",
    customerPhone: "(650) 492-7714",
    vehicleType: "suv",
    vehicleDetails: {
      year: "2025",
      make: "Mercedes-AMG",
      model: "G63",
      color: "Magno Night Black (Matte)",
    },
    servicePackageId: "ceramic-signature",
    addons: ["interior-coating", "wheel-ceramic"],
    totalPrice: 2130,
    depositAmount: 450,
    scheduledDate: "2026-10-24",
    timeSlot: "01:30 PM",
    bayId: "bay-2",
    status: "in_bay",
    leadSource: "Meta Ad: 5Y Ceramic",
    followUpStep: 4,
    notes: "Matte finish requires specialized matte-specific ceramic and no abrasive polishes.",
    isMobileService: false,
  },
  {
    id: "LX-72155",
    createdAt: "2026-10-04T08:20:00Z",
    customerName: "Marcus Sterling",
    customerEmail: "m.sterling@sterlingcap.com",
    customerPhone: "(408) 321-9980",
    vehicleType: "sedan",
    vehicleDetails: {
      year: "2023",
      make: "Bentley",
      model: "Flying Spur W12",
      color: "Dark Sapphire",
    },
    servicePackageId: "interior-executive",
    addons: ["ozone-sterilization"],
    totalPrice: 635,
    depositAmount: 150,
    scheduledDate: "2026-10-14",
    timeSlot: "09:00 AM",
    bayId: "bay-3",
    status: "quote_sent",
    leadSource: "Meta Ad: Executive Fleet",
    followUpStep: 1,
    notes: "Quote sent via SMS & Email. Holding VIP slot for 48 hours.",
    isMobileService: true,
  },
  {
    id: "LX-61294",
    createdAt: "2026-10-04T12:05:00Z",
    customerName: "Derrick Thorne",
    customerEmail: "dthorne@sftransitpartners.com",
    customerPhone: "(510) 708-4100",
    vehicleType: "fleet",
    vehicleDetails: {
      year: "2024",
      make: "Cadillac",
      model: "Escalade ESV Chauffeur (x4 units)",
      color: "Black Onyx",
    },
    servicePackageId: "fleet-shield",
    addons: ["glass-coating", "interior-coating"],
    totalPrice: 2840,
    depositAmount: 600,
    scheduledDate: "2026-10-30",
    timeSlot: "08:00 AM",
    bayId: "mobile-unit",
    status: "new_inquiry",
    leadSource: "Meta Ad: Executive Fleet",
    followUpStep: 1,
    notes: "Inquiry for corporate fleet contract renewal. Dispatching B2B proposal packet.",
    isMobileService: true,
  },
];

export const INITIAL_FLEET_ACCOUNTS: FleetAccount[] = [
  {
    id: "FL-101",
    companyName: "Blackline Chauffeur & Limousine",
    contactPerson: "Derrick Thorne",
    email: "ops@blacklinevip.com",
    phone: "(415) 790-1120",
    totalVehicles: 8,
    contractTier: "Platinum Corporate (Weekly)",
    monthlyRetainer: 4800,
    activeStatus: "active",
    lastServiceDate: "2026-09-28",
    nextScheduledDate: "2026-10-08",
  },
  {
    id: "FL-102",
    companyName: "Silverstone Exotic Rentals",
    contactPerson: "Tariq Al-Mansoor",
    email: "tariq@silverstone-exotics.com",
    phone: "(408) 554-9210",
    totalVehicles: 12,
    contractTier: "Titanium Executive",
    monthlyRetainer: 7200,
    activeStatus: "active",
    lastServiceDate: "2026-10-01",
    nextScheduledDate: "2026-10-12",
  },
  {
    id: "FL-103",
    companyName: "Bayview Executive Airport Transfers",
    contactPerson: "Rachel Bennett",
    email: "rachel@bayviewtransfers.com",
    phone: "(650) 330-8740",
    totalVehicles: 6,
    contractTier: "Gold Fleet (Bi-Weekly)",
    monthlyRetainer: 3100,
    activeStatus: "renewal_due",
    lastServiceDate: "2026-09-20",
    nextScheduledDate: "2026-10-06",
  },
];

export const QUOTE_DRIP_STEPS: QuoteDripStep[] = [
  {
    step: 1,
    delayHours: 0,
    title: "Instant Personalized Estimate + 48-Hour Slot Hold",
    channel: "SMS",
    contentPreview: "Hi Julian, your bespoke quote for the Porsche 911 GT3 RS with 5-Year Graphene Ceramic is ready ($2,350). Your VIP Bay 1 slot for Oct 18 is held for 48 hrs. Tap to lock your bay: luxeauto.com/r/LX-94821",
    conversionGoal: "Instant deposit lock before slot release",
  },
  {
    step: 2,
    delayHours: 24,
    title: "Before & After Video Case Study Proof",
    channel: "EMAIL",
    contentPreview: "Subject: Inside the Studio: 50/50 Paint Correction on a 911 GT3 RS. See how our 10H ceramic system withstands track rubber, UV fading, and high heat with 0 swirls.",
    conversionGoal: "Build irresistible emotional proof & authority",
  },
  {
    step: 3,
    delayHours: 48,
    title: "Final Urgency Call: Bay Releasing to Waitlist",
    channel: "SMS",
    contentPreview: "Julian, our Oct calendar is 87% booked and 2 other clients requested this exact weekend slot. Would you like us to confirm your reservation or release it to the waitlist?",
    conversionGoal: "Scarcity trigger to secure deposit",
  },
];
